#+title: Emacs Configuration
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el

* Stuff to do
** TODO Eglot
** TODO Performance. Defer loading and stuff.

* Lexical binding comment for both early-init and init
  I'm too lazy to write some code to tangle to both files.
  #+begin_src emacs-lisp :tangle ./early-init.el
    ;; -*- lexical-binding: t -*-
  #+end_src
  #+begin_src emacs-lisp
    ;; -*- lexical-binding: t -*-
  #+end_src

* Early init
  #+begin_src emacs-lisp :tangle ./early-init.el
    (setq read-process-output-max (* 1024 1024 3))
    (add-hook 'emacs-startup-hook
              (let ((old-threshold gc-cons-threshold))
                (lambda ()
                  (setq gc-cons-threshold old-threshold))))
    (setq gc-cons-threshold most-positive-fixnum)

    (add-hook 'emacs-startup-hook
              (lambda ()
                (message "Emacs ready in %s with %d garbage collections." (emacs-init-time) gcs-done)))
  #+end_src

* User Information
  #+begin_src emacs-lisp
    (setq user-full-name "Queyenth")
    (setq user-mail-address "q@queyenth.xyz")
  #+end_src

* Native Comp
  #+begin_src emacs-lisp
    (setq comp-deferred-compilation t)
  #+end_src

* After Make Frame
  Because I use =emacs --daemon=, I need to set some stuff after frame
  is created (otherwise it doesn't work).
  #+begin_src emacs-lisp
    (defun q/after-frame (&optional frame)
      (set-face-attribute 'default nil :font "Iosevka" :height 110))

    (add-hook 'after-make-frame-functions #'q/after-frame)

    (set-frame-parameter (selected-frame) 'alpha '(100 . 100))
    (add-to-list 'default-frame-alist '(alpha . (100 . 100)))
  #+end_src

* Package manager configuration
  Let's add org/melpa/melpa-stable archives.
  #+begin_src emacs-lisp
    (require 'package)

    (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
    (add-to-list 'package-archives '("nongnu" . "https://elpa.nongnu.org/nongnu/"))

    (setq package-enable-at-startup nil)
    (package-initialize)
  #+end_src

  If there's no archive - download it.
  #+begin_src emacs-lisp
    (when (not package-archive-contents)
      (package-refresh-contents))
  #+end_src

  Just a function to fetch a package if it's not installed yet. I used
  [[https://github.com/jwiegley/use-package/][use-package]] before, but I don't really need it. All I need is
  =package-install=.
  #+begin_src emacs-lisp
    (defun q/ensure-package (package)
      (unless (package-installed-p package)
        (package-install package)))
  #+end_src

* Move the custom settings out of init.el
  #+begin_src emacs-lisp
    (setq custom-file (concat user-emacs-directory "emacs-custom.el"))
    (load custom-file)
  #+end_src

* Set UID environment variable
  #+begin_src emacs-lisp
    (setenv "UID" (string-trim (shell-command-to-string "id -u")))
  #+end_src

* Changes of defaults I don't like
  #+begin_src emacs-lisp
    (fset 'yes-or-no-p 'y-or-n-p)
    (setq create-lockfiles nil)
    (setq-default save-place t)
    (setq save-place-file (concat user-emacs-directory "places"))
    (setq backup-directory-alist `(("." .,(concat user-emacs-directory "backups"))))
    (setq enable-recursive-minibuffers t)

    (setq
     x-select-enable-clipboard t
     x-select-enable-primary t
     save-interprogram-paste-before-kill t
     apropos-do-all t
     mouse-yank-at-point t)
    (setq-default cursor-type 'bar)
    (setq ring-bell-function 'ignore)
  #+end_src

* Amazing default modes I need enabled
  #+begin_src emacs-lisp
    (column-number-mode)
    (show-paren-mode 1)
    (savehist-mode)
    (auto-save-visited-mode)
    (global-auto-revert-mode)
    (global-so-long-mode 1)
    (pixel-scroll-precision-mode)
  #+end_src

* Not so amazing default modes I need disabled
  #+begin_src emacs-lisp
    (setq inhibit-startup-message t)
    (progn
      (menu-bar-mode -1)
      (when (fboundp 'tool-bar-mode)
        (tool-bar-mode -1))
      (when (fboundp 'scroll-bar-mode)
        (scroll-bar-mode -1))
      (tooltip-mode -1))
    (set-fringe-mode 0)

    (blink-cursor-mode 0)
  #+end_src

* Password management and pinentry
  Don't forget to put =allow-emacs-pinentry= to =~/.gnupg/gpg-agent.conf=
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'pinentry)
      (require 'pinentry)
      (pinentry-start))
  #+end_src
  Pass is good. Pass is love.
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'pass)
      (require 'pass))
  #+end_src

* EPA
  EPA stand for EasyPG Assistant. I guess.
  #+begin_src emacs-lisp
    (setq epa-file-encrypt-to user-mail-address)
  #+end_src

* Minions
  Basically, it hides all the minor modes in modeline, and adds a =;-=
  which has all of them! Cute!
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'minions)
      (require 'minions)
      (minions-mode 1))
  #+end_src

* Word Count Mode
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'wc-mode)
      (require 'wc-mode)
      (add-to-list 'minions-whitelist '(wc-mode)))
  #+end_src

* Which key
  Shows the keybindings in a minibuffer when you're lost. You pressed
  something, but don't remember what you have to press next, and here
  comes which-key
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'which-key)
      (require 'which-key)
      (which-key-mode))
  #+end_src

* Rainbow delimiters
  There's a lot of delimiters in lisp files. And pretty much
  everywhere. It's cool to distinguish them by color. So rainbow, so
  wow.
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'rainbow-delimiters)
      (require 'rainbow-delimiters)
      (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))
  #+end_src

* Ansi Color for compilation buffer
  By default, compilation buffer does not parse colors. But I need
  them! You see red, you know you messed up. You see green, you feel
  good.
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'ansi-color)
      (require 'ansi-color)
      (defun q/colorize-compilation-buffer ()
        (when (eq major-mode 'compilation-mode)
          (ansi-color-apply-on-region compilation-filter-start (point-max))))
      (add-hook 'compilation-filter-hook #'q/colorize-compilation-buffer)
      (setq compilation-scroll-output t))
  #+end_src

* Line numbers
  I don't want relative line numbers. They are slow, they are not
  practical, they exists only for screenshots or something.
  #+begin_src emacs-lisp
    (progn
      (setq display-line-numbers-type t)
      (add-hook 'prog-mode-hook #'display-line-numbers-mode))
  #+end_src

* Colortheme
  This part changes a lot, so just go along, it doesn't matter.
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'ef-themes)
      (mapc #'disable-theme custom-enabled-themes)
      (load-theme 'ef-day :no-confirm))
  #+end_src

* Writeroom mode
  Sometimes I write stuff, and I'm like 'boy, there's a lot of
  distraction stuff on the screen, and that's why all my passages
  sucks!'. But writeroom mode didn't improve my writing at all, I
  don't know why.
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'writeroom-mode)
      (require 'writeroom-mode))
  #+end_src

* Icons
  Okay, icons. Yes, I need some gui-eye-candy-stuff, don't judge me.
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'all-the-icons)
      (require 'all-the-icons))
  #+end_src

* Tabs
  I use spaces instead of tabs. I like tabs, I feel they suit better
  for indentation, cause of semantic meaning behind them (indent,
  duh). I like spaces, because they are the same everywhere.
  #+begin_src emacs-lisp
    (setq custom-tab-width 4)
    (setq tab-width 4)
    (setq-default indent-tabs-mode nil)
    (setq-default evil-shift-width custom-tab-width)
    (setq-default electric-indent-inhibit t)
  #+end_src
  
  Also, I think =Tab= key is good for complete AND indent. So here we
  go.
  #+begin_src emacs-lisp
    (setq tab-always-indent 'complete)
  #+end_src

  And delete four spaces in a single =Backspace= press. Cause it would
  be stupid to delete one indent pressing =Backspace= four times. Really
  stupid.
  #+begin_src emacs-lisp
    (setq backward-delete-char-untabify-method 'hungry)
  #+end_src

* Undo Tree
  Wow, this is good. Honestly, I need this for evil, but sometimes I
  do =M-x undo-tree-visualize= and it's fun thing to do.
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'undo-tree)
      (require 'undo-tree)
      (global-undo-tree-mode)
      (setq undo-tree-history-directory-alist `(("." . ,(concat user-emacs-directory "undo-tree")))))
  #+end_src

* General
  Aye aye Captain! Here comes the General! Basically, I just use it to
  handle prefix easier. I probably can live without it, but if you
  read this - I didn't manage too. Oh well.
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'general)
      (with-eval-after-load 'evil
        (require 'general)
        (general-evil-setup t)

        (general-create-definer q/leader-keys
          :keymaps '(normal insert visual emacs)
          :prefix "SPC"
          :global-prefix "C-SPC")))
  #+end_src

* EVIL
  I use evil, cause I used vim for like 10 years or something, so I
  just can't live without it. But hey, emacs keys are good too, I even
  know some! We also have some funny bindings. I bind =C-u= for normal
  evil state, cause =evil-want-C-u-scroll= didn't do it for me. I don't
  know why, I just accept some things and move on, you know? And =C-h=
  for insert evil state, cause =Backspace= key is so far away from home
  row, I just can't reach it with my smol hands.
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'evil)
      (setq evil-want-integration t)
      (setq evil-want-keybinding nil)
      (setq evil-undo-system 'undo-tree)
      (setq evil-search-module 'evil-search)
      (setq evil-ex-complete-emacs-commands nil)
      (setq evil-vsplit-window-right t)
      (setq evil-vsplit-window-below t)
      (setq evil-shift-round nil)
      (setq evil-want-C-u-scroll t)
      (require 'evil)
      (evil-define-key 'normal 'global (kbd "C-u") 'evil-scroll-up)
      (evil-define-key 'insert 'global (kbd "C-h") 'evil-delete-backward-char-and-join)
      (evil-define-key 'normal 'global (kbd "RET") 'evil-ret-and-indent)
      (evil-mode))
  #+end_src

** Evil collection
   Here comes a ton of bindings for a ton of modes. It has everything,
   even [[*Magit][Magit]]. You definitely need this. Or maybe not.
   #+begin_src emacs-lisp
     (progn
       (q/ensure-package 'evil-collection)
       (with-eval-after-load 'evil
         (require 'evil-collection)
         (evil-collection-init)))
   #+end_src

** Evil surround
   That's a cool package, inspired by [[https://github.com/tpope/vim-surround][vim-surround]]. You do =ysiw"= and
   the word under your cursor gets surrounded by ="= character. You can
   do brackets and other operator, like surround setence. Also it can
   change the surrounded characters to something else with =cs'"= to
   change ='= to ="=!
   #+begin_src emacs-lisp
     (progn
       (q/ensure-package 'evil-surround)
       (with-eval-after-load 'evil
         (require 'evil-surround)
         (evil-define-key 'operator global-map "s" 'evil-surround-edit)
         (evil-define-key 'operator global-map "S" 'evil-Surround-edit)
         (evil-define-key 'visual global-map "S" 'evil-surround-region)
         (evil-define-key 'visual global-map "gS" 'evil-Surround-region)))
   #+end_src

** Evil commentary
   Just to comment a bunch of lines. Sometimes I still do something
   like =^<C-v>4jI;= to comment four lines with =;=, but I definitely
   should just use evil-commentary.
   #+begin_src emacs-lisp
     (progn
       (q/ensure-package 'evil-commentary)
       (with-eval-after-load 'evil
         (require 'evil-commentary)
         (evil-commentary-mode)
         (with-eval-after-load 'general
           (q/leader-keys "'" '(evil-commentary-line :which-key "comment line(s)")))))
   #+end_src

* Dired
  You know Dired, right? Everyone knows Dired. If you don't - go and
  meet him. He's cool. He allows you to manage folder and files and stuff.
  #+begin_src emacs-lisp
    (progn
      (setq dired-dwim-target t)
      (progn
        (q/ensure-package 'dired-single)
        (require 'dired-single)
        (with-eval-after-load 'evil-collection
          (evil-collection-define-key 'normal 'dired-mode-map
            "h" 'dired-single-up-directory
            "l" 'dired-single-buffer))))
  #+end_src

  And here are cool gui-candys for Dired, cause he deserves it.
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'all-the-icons-dired)
      (require 'all-the-icons-dired)
      (add-hook 'dired-mode-hook #'all-the-icons-dired-mode))
  #+end_src

  Some keybindings for Dired, cause I want to be only few keystrokes
  away from him.
  #+begin_src emacs-lisp
    (with-eval-after-load 'general
      (q/leader-keys
        "d" '(:ignore t :which-key "Dired")
        "dd" '(dired :which-key "dwim")
        "do" '(dired-other-window :which-key "other window")))
  #+end_src

* Calendar
** Location
  #+begin_src emacs-lisp
    (setq calendar-latitude 54.99244)
    (setq calendar-longitude 73.36859)
    (setq calendar-week-start-day 1)
  #+end_src
** Helpers
   #+begin_src emacs-lisp
     (defun q/last-day-of-week-of-month-p (date day-of-week)
       (let ((today-of-week (calendar-day-of-week date))
             (month (calendar-extract-month date))
             (next-week-month (calendar-extract-month (calendar-gregorian-from-absolute (+ (calendar-absolute-from-gregorian date) 7)))))
         (and
          (eq today-of-week day-of-week)
          (not (eq next-week-month month)))))
   #+end_src
   

* Org
  Best things in my life happened thanks to Org. I mean it. My parents
  think that I'm a grown up, my friends think I'm boring when I tell them I
  can't go grab a beer, cause there's a lot of stuff on my agenda for
  tomorrow. But anyway, it's a good thing to be organized, gives you
  an illusion of having control over your life, and sometimes all you
  have is an illusion and you hang in there... So, here we go with
  configuration. Let's start with a helper function, just to fetch
  file from [[https://syncthing.net][Syncthing]]. Ah, yes, about that. I sync my devices and
  files through [[https://syncthing.net][Syncthing]]. It's good, sometimes my files are still
  there when I deleted them, but overall, it works fine, and it's on
  my devices, no 3rd party stuff.
  #+begin_src emacs-lisp
    (setq q/org-directory (concat (getenv "SYNCTHING") "org"))
    (defun q/get-org-file (file)
      (concat q/org-directory file))
  #+end_src

  And now for Org itself. It has a lot of things, but they are
  self-explanationary, I think.
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'org)
      (require 'org)
      (setq org-log-into-drawer t)
      (setq org-log-reschedule 'note)
      (setq org-refile-allow-creating-parent-nodes 'confirm)
      (setq org-refile-use-outline-path 'file)
      (setq org-outline-path-complete-in-steps nil)
      (setq org-indent-indentation-per-level 1)
      (setq org-adapt-indentation t)
      (setq org-hide-leading-stars t)
      (setq org-hide-emphasis-markers t)
      (setq org-blank-before-new-entry '((heading . nil) (plain-list-item . nil)))
      (setq org-cycle-separator-lines 1)
      (setq org-startup-with-inline-images t)
      (setq org-directory q/org-directory)
      (add-to-list 'org-modules 'habits)
      (setq org-agenda-files (list org-directory))
      (setq org-refile-targets '(("next.org" :level . 0)
                                 ("projects.org" :maxlevel . 1)
                                 ("life.org" :level . 0)))

      (setq org-todo-keywords
            '((sequence "TODO(t)" "NEXT(n)" "WAIT(w@/!)" "|" "DONE(d!)" "CANCELED(c@)")))

      (setq org-return-follow-links t)

      (org-babel-do-load-languages
       'org-babel-load-languages
       '((emacs-lisp . t)
         (python . t)))

      (setq org-confirm-babel-evaluate nil)
      (setq org-src-tab-acts-natively t)
      (require 'ox-md)

      (require 'org-tempo)
      (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
      (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
      (add-to-list 'org-structure-template-alist '("py" . "src python")))
  #+end_src

** Org Crypt
   #+begin_src emacs-lisp
     (with-eval-after-load 'org
       (org-crypt-use-before-save-magic))
   #+end_src

** Org Agenda
   Some custom agendas to see what I should do today, what's in my
   inbox to refile, and stuff.
   #+begin_src emacs-lisp
     (progn
       (setq q/org-agenda-todo-view
             `(("A" "Agenda"
                ((agenda ""
                         ((org-agenda-span 'day)
                          (org-deadline-warning-days 365)))
                 (todo "TODO"
                       ((org-agenda-overriding-header "To Refile")
                        (org-agenda-files `(,(q/get-org-file "/inbox.org")))))
                 (todo "NEXT"
                       ((org-agenda-overriding-header "In Progress")
                        (org-agenda-files `(,(q/get-org-file "/next.org")
                                            ,(q/get-org-file "/projects.org")))))
                 (todo "WAIT"
                       ((org-agenda-overriding-header "Waiting")
                        (org-agenda-files `(,(q/get-org-file "/next.org")
                                            ,(q/get-org-file "/projects.org")))))
                 nil))))
       (setq org-agenda-custom-commands `,q/org-agenda-todo-view)
       (advice-add 'org-refile :after
                   (lambda (&rest _)
                     (org-save-all-org-buffers))))
   #+end_src

** Org Capture
   Capture is important. You have to free up your mind in order to
   concentrate on stuff, and it helps you to remember stuff. Your
   brain is not for storing ideas, its for generating them.
   #+begin_src emacs-lisp
     (with-eval-after-load 'org
       (setq org-capture-templates
             `(("i" "inbox" entry (file ,(q/get-org-file "/inbox.org"))
                (file ,(q/get-org-file "/tmpl/task")) :immediate-finish t)
               ("l" "link" entry (file ,(q/get-org-file "/inbox.org"))
                (file ,(q/get-org-file "/tmpl/link")) :immediate-finish t))))
   #+end_src

** Org Drill
   That's a package for [[https://en.wikipedia.org/wiki/Spaced_repetition][spaced repetition]] in Org mode. I use it
   mainly for languages and rubik's cube algorithms. I think about
   using it for handling inbox, like [[https://andymatuschak.org/][Andy Matuschak]] does. Dunno.
   #+begin_src emacs-lisp
     (progn
       (q/ensure-package 'org-drill)
       (with-eval-after-load 'org
         (require 'org-drill)
         (setq org-drill-add-random-noise-to-intervals-p t)
         (setq org-drill-learn-fraction 0.25)
         (setq org-drill-hint-separator "||")
         (setq org-drill-left-cloze-delimiter "<[")
         (setq org-drill-right-cloze-delimiter "]>")))
   #+end_src

** Org Download
   I use this to paste images in org files from clipboard, cause I'm
   lazy to manage files and stuff.
   #+begin_src emacs-lisp
     (progn
       (q/ensure-package 'org-download)
       (with-eval-after-load 'org
         (require 'org-download)))
   #+end_src

** Org Cliplink
   Extension to create org-mode links from clipboard with HTML title
   as text. I use it in =org-capture= to save links.
   #+begin_src emacs-lisp
     (progn
       (q/ensure-package 'org-cliplink)
       (with-eval-after-load 'org
         (require 'org-cliplink)))
   #+end_src

** Evil Org
   Looks like [[*Evil collection][evil-collection]] doesn't have bindings for =org-mode=. So
   here it is.
   #+begin_src emacs-lisp
     (progn
       (q/ensure-package 'evil-org)
       (with-eval-after-load 'evil
         (with-eval-after-load 'org
           (require 'evil-org)
           (require 'evil-org-agenda)
           (evil-org-agenda-set-keys)))
       (add-hook 'org-mode-hook #'evil-org-mode))
   #+end_src

** Org Toggl
   #+begin_src emacs-lisp
     (progn
       (setq org-toggl-inherit-toggl-properties t)
       (add-to-list 'load-path (concat user-emacs-directory "custom"))
       (require 'org-toggl)
       (toggl-get-projects)
       (org-toggl-integration-mode))

     (defun q/toggl-get-projects ()
       (interactive)
       (toggl-get-projects))
   #+end_src

** Org Keybindings
   Just keybindings.
   #+begin_src emacs-lisp
     (q/leader-keys
       "o" '(:ignore t :which-key "Org")
       "oa" '(org-agenda :which-key "agenda")
       "oc" '(org-capture :which-key "capture")
       "od" '(org-drill :which-key "drill")
       "op" '(org-download-clipboard :which-key "clipboard image")
       "os" '(org-save-all-org-buffers :which-key "save all org buffers")
       "oz" '(org-revert-all-org-buffers :which-key "revert all org buffers")
       "ot" '(:ignore t :which-key "Time Tracking")
       "oti" '(org-clock-in :which-key "clock in")
       "oto" '(org-clock-out :which-key "clock out"))
   #+end_src

* Expand Region
  This is cool package to expand your visual selection semantically. I
  guess.
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'expand-region)
      (require 'expand-region)
      (q/leader-keys "=" '(er/expand-region :which-key "expand region")))
  #+end_src

* Vertico
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'vertico)
      (require 'vertico)
      (vertico-mode)
      (setq vertico-cycle t))
  #+end_src
** Orderless
   #+begin_src emacs-lisp
     (progn
       (q/ensure-package 'orderless)
       (require 'orderless)
       (setq completion-styles '(orderless)
             completion-category-defaults nil
             completion-category-overrides '((file (styles partial-completion)))))
   #+end_src
   #+begin_src emacs-lisp
     (setq read-file-name-completion-ignore-case t
           read-buffer-completion-ignore-case t
           completion-ignore-case t)
   #+end_src
** Marginalia
   Adds some cool context to completion candidats in minibuffer (like
   size of files when you do =find-file= and stuff).
   #+begin_src emacs-lisp
     (progn
       (q/ensure-package 'marginalia)
       (require 'marginalia)
       (marginalia-mode))
   #+end_src

* Embark
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'embark)
      (global-set-key (kbd "C-.") 'embark-act)
      (global-set-key (kbd "M-,") 'embark-dwim))
  #+end_src

* Company
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'company)
      (require 'company)
      (setq company-tooltip-limit 5)
      (setq company-idle-delay 0.1)
      (setq company-minimum-prefix-length 3)
      (setq company-selection-wrap-around t)
      (setq company-require-match 'never)
      (add-to-list 'company-backends 'company-capf)
      (add-hook 'after-init-hook #'global-company-mode))
  #+end_src

* Project.el
  Built-in project management mode. I used =projectile= before, but
  didn't use even 80% of what it has to offer. So settled down with
  =project.el=.
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'project)
      (require 'project)
      (q/leader-keys "p" '(:keymap project-prefix-map :which-key "project")))
  #+end_src

* Popper
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'popper)
      (require 'popper)
      (global-set-key (kbd "C-<escape>") 'popper-toggle-latest)
      (global-set-key (kbd "M-<escape>") 'popper-cycle)
      (setq popper-reference-buffers
            '(help-mode
              compilation-mode
              "\\* docker"))
      (setq popper-group-function #'popper-group-by-project)
      (popper-mode +1)
      (popper-echo-mode +1))
  #+end_src

* Find File in project
  You do your work. You need to open some file in your project. Sounds
  familiar, doesn't it? Here you go, =find-file-in-project=.
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'find-file-in-project)
      (require 'find-file-in-project)
      (setq ffip-use-rust-fd t))
  #+end_src

* RipGrep
  You do your work. You need to search for some string in your
  project. Sounds familiar, doesn't it? (that sentence sounds familiar
  too...).
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'rg)
      (require 'rg)
      (with-eval-after-load 'project
        (define-key project-prefix-map "s" #'rg-project)))
  #+end_src

  Also use ripgrep for =xref=.
  #+begin_src emacs-lisp
    (setq xref-search-program 'ripgrep)
  #+end_src

* FZF
  [[https://github.com/junegunn/fzf][FZF]] is cool fuzzy matching cli tool you want to use. It just clicks
  with me, I don't know.
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'fzf)
      (setenv "FZF_DEFAULT_COMMAND" "fd --type f")
      (require 'fzf)
      (q/leader-keys "z" '(fzf-find-file :which-key "FZF find file"))
      (q/leader-keys "b" '(fzf-switch-buffer :which-key "FZF switch buffer"))
      (defun fzf-no-ignore ()
        (interactive)
        (setenv "FZF_DEFAULT_COMMAND" "fd --no-ignore --type f"))
      (defun fzf-ignore ()
        (interactive)
        (setenv "FZF_DEFAULT_COMMAND" "fd --type f"))
      (with-eval-after-load 'project
        (defun project-fzf ()
          (interactive)
          (let ((project (project-current t)))
            (fzf-find-file-in-dir (project-root project))))
        (define-key project-prefix-map "z" #'project-fzf)))
  #+end_src

* Magit
  Wow. Magit is good. I don't know how to live without it. It's git
  interface made right. I love it. I even love you, cause I'm full of
  love right now, when I think about =Magit=.
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'magit)
      (require 'magit)
      (q/leader-keys "g" '(magit-status :which-key "magit"))
      (with-eval-after-load 'project
        (define-key project-prefix-map "m" #'magit-status)
        (add-to-list 'project-switch-commands '(magit-status "Magit"))))
  #+end_src

** Magit todos
   Shows the TODO/FIXME entries from the project source code in magit buffer.
   #+begin_src emacs-lisp
     (progn
       (q/ensure-package 'magit-todos)
       (require 'magit-todos))
   #+end_src

* RSS
  I get my news through RSS. I like RSS.
  #+begin_src emacs-lisp
    (progn
      (q/ensure-package 'elfeed)
      (require 'elfeed)
      (setq elfeed-feeds '(
                           ("https://lithub.com/feed" lithub)
                           ("https://news.ycombinator.com/rss" hackernews)
                           ))
      (setq elfeed-search-filter "@7-days-ago")
      (setq elfeed-search-title-max-width 100)
      (setq elfeed-search-title-min-width 100))
  #+end_src

* Some coding stuff
  Yes, I do code sometimes.

** Flycheck
   You need your code being checked, and flycheck flychecks your code.
   #+begin_src emacs-lisp
     (progn
       (q/ensure-package 'flycheck)
       (require 'flycheck)
       (add-hook 'prog-mode-hook #'global-flycheck-mode))
   #+end_src

** Electric Pair Mode
   You write open bracket, and get close bracket. Fun? Sure.
   #+begin_src emacs-lisp
     (progn
       (add-hook 'prog-mode-hook #'electric-pair-mode))
   #+end_src

** Docker
   #+begin_src emacs-lisp
     (progn
       (q/ensure-package 'docker)
       (require 'docker)
       (defun q/force-evil-state-for-docker-compose ()
         (if (string-match "^\\* docker-compose.*" (buffer-name))
             (evil-force-normal-state)))
       (defun q/kill-all-exec-buffers ()
         (interactive)
         (kill-matching-buffers "\* docker-compose exec" nil t))

       (add-hook 'shell-mode-hook #'q/force-evil-state-for-docker-compose))
   #+end_src

** Treesitter
   Great package! It knows stuff about languages, so offers a better
   syntax highlighting.
   #+begin_src emacs-lisp
     (progn
       (q/ensure-package 'tree-sitter)
       (q/ensure-package 'tree-sitter-langs)
       (require 'tree-sitter)
       (require 'tree-sitter-langs)
       (global-tree-sitter-mode)
       (add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode))
   #+end_src

** LSP
   #+begin_src emacs-lisp
     (progn
       (q/ensure-package 'lsp-mode)
       (setq lsp-headerline-breadcrumb-enable nil)
       (setq lsp-intelephense-multi-root nil)
       (setq lsp-file-watch-threshold nil)
       (require 'lsp-mode)
       (with-eval-after-load 'lsp-mode
         (q/ensure-package 'lsp-ui)
         (require 'lsp-ui))
       (add-hook 'lsp-mode-hook #'lsp-enable-which-key-integration))
   #+end_src

** DAP
   So debuggin, huh?
   #+begin_src emacs-lisp
     (progn
       (q/ensure-package 'dap-mode)
       (require 'dap-mode)
       (dap-auto-configure-mode)
       (require 'dap-php))
   #+end_src

** YASnippet
   #+begin_src emacs-lisp
     (progn
       (q/ensure-package 'yasnippet)
       (require 'yasnippet)
       (yas-global-mode 1))

     (with-eval-after-load 'yasnippet
       (q/ensure-package 'yasnippet-snippets))

     (q/ensure-package 's)

     (defun q/yas-magento-get-namespace-path ()
       (let* ((file-path (file-name-directory (or (buffer-file-name)
                                                  (buffer-name (current-buffer)))))
              (namespace (s-replace "/" "\\" (and (string-match ".*/app/code/\\(.*\\)/" file-path)
                                                  (match-string 1 file-path)))))
         namespace))
   #+end_src

** Languages
*** Web
    #+begin_src emacs-lisp
      (progn
        (q/ensure-package 'web-mode)
        (require 'web-mode))
    #+end_src

*** PHP
    Yes, PHP.
    #+begin_src emacs-lisp
      (progn
        (q/ensure-package 'php-mode)
        (require 'php-mode)
        (add-hook 'php-mode-hook #'lsp-deferred))
    #+end_src
**** Magento
     #+begin_src emacs-lisp
       (defun q/magento (command)
         (interactive (list
                       (read-string "Command: ")))
         (docker-compose-run-docker-compose-async-with-buffer "exec" '() "fpm" (concat "php -d memory_limit=4G bin/magento" " " command)))

       (defun q/magento-clear-cache ()
         (interactive)
         (q/magento "cache:flush"))

       (defun q/magento-static-content-deploy (langs)
         (interactive (list
                       (read-string "Locales: " nil nil "en_US en_GB")))
         (q/magento (concat "setup:static-content:deploy -f " langs)))

       (defun q/magento-di-compile ()
         (interactive)
         (q/magento "setup:di:compile"))

       (defun q/magento-setup-upgrade ()
         (interactive)
         (q/magento "setup:upgrade"))

       (q/leader-keys
         "m" '(:ignore t :which-key "Magento")
         "mm" '(q/magento :which-key "run some command")
         "mc" '(q/magento-clear-cache :which-key "clear cache")
         "ms" '(q/magento-static-content-deploy :which-key "static content deploy")
         "md" '(q/magento-di-compile :which-key "DI compile")
         "mu" '(q/magento-setup-upgrade :which-key "setup upgrade"))
     #+end_src

*** XML
    #+begin_src emacs-lisp
      (setq nxml-child-indent 4)
    #+end_src

*** TypeScript
    #+begin_src emacs-lisp
      (progn
        (q/ensure-package 'typescript-mode)
        (require 'typescript-mode)
        (add-hook 'typescript-mode-hook #'lsp-deferred))
    #+end_src

* Denote
  Prot is genius.
  #+begin_src emacs-lisp
    (setq q/notes-directory (concat q/org-directory "/notes"))
    (progn
      (q/ensure-package 'denote)
      (setq denote-directory q/notes-directory)
      (setq denote-known-keywords '("emacs" "book" "idea" "philosophy"))
      (setq denote-infer-keywords nil))

    (defun q/find-note ()
      (interactive)
      (let ((default-directory (concat (string-trim-right denote-directory "/") "/")))
            (call-interactively 'find-file)))

      (with-eval-after-load 'general
        (q/leader-keys
          "n" '(:ignore t :which-key "Denote")
          "nn" '(denote :which-key "new")
          "nl" '(denote-link :which-key "link")
          "nb" '(denote-link-backlinks :which-key "backlinks")
          "no" '(q/find-note :which-key "find")))
  #+end_src
