#+title: Emacs Configuration
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el

* Server Start
  #+begin_src emacs-lisp
    (server-start)
  #+end_src

* Package manager configuration
  Here we just add some package archives and install use-package.
  #+begin_src emacs-lisp
    (require 'package)

    (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/"))
    (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
    (add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/"))

    (setq package-enable-at-startup nil)
    (package-initialize)

    (unless (package-installed-p 'use-package)
      (package-refresh-contents)
      (package-install 'use-package))

    (eval-when-compile
      (require 'use-package))

    (setq use-package-always-ensure t)
  #+end_src

* Some basic settings to change from default
  #+begin_src emacs-lisp
    (fset 'yes-or-no-p 'y-or-n-p)
    (setq create-lockfiles nil)
    (setq-default save-place t)
    (setq save-place-file (concat user-emacs-directory "places"))

    (setq backup-directory-alist `(("." . ,(concat user-emacs-directory "backups"))))
    (auto-save-visited-mode)

    (column-number-mode)
  #+end_src
  Turn on auto-fill mode by default for all text-mode
  #+begin_src emacs-lisp
    (add-hook 'text-mode-hook 'turn-on-auto-fill)
  #+end_src
  Move customizations to another file, cause it makes me mad to see
  them in init.el
  #+begin_src emacs-lisp
    (setq custom-file "~/.emacs.d/emacs-custom.el")
    (load custom-file)
  #+end_src
  Some performance stuff
  #+begin_src emacs-lisp
    (setq read-process-output-max (* 1024 1024 3))
    (setq gc-cons-threshold 100000000)
  #+end_src

* Some helping stuff
** Diminish
   #+begin_src emacs-lisp
     (use-package diminish)
   #+end_src
** Which-key
   which-key is a package that shows you the small window with all the
   variants of key chord you can do, with either description of that
   key or its function name
   #+begin_src emacs-lisp
     (use-package which-key
       :diminish
       :config
       (which-key-mode))
   #+end_src

* UI
** Basic UI settings
   #+begin_src emacs-lisp
     (setq inhibit-startup-message t)
     (menu-bar-mode -1)
     (when (fboundp 'tool-bar-mode)
       (tool-bar-mode -1))
     (when (fboundp 'scroll-bar-mode)
       (scroll-bar-mode -1))
     (tooltip-mode -1)
     (set-fringe-mode 0)

     (setq
      x-select-enable-clipboard t
      x-select-enable-primary t
      save-interprogram-paste-before-kill t
      apropos-do-all t
      mouse-yank-at-point t)
     (blink-cursor-mode 0)
     (setq-default cursor-type 'bar)
     (setq ring-bell-function 'ignore)
   #+end_src
** Font
   #+begin_src emacs-lisp
     (set-face-attribute 'default nil :font "Go Mono" :height 100)
   #+end_src
** Rainbow delimiters
   #+begin_src emacs-lisp
     (use-package rainbow-delimiters
       :diminish
       :hook (prog-mode . rainbow-delimiters-mode))
   #+end_src
** Ansi Color for compilation buffer
   #+begin_src emacs-lisp
     (use-package ansi-color
       :config
       (defun qqq/colorize-compilation-buffer ()
	 (when (eq major-mode 'compilation-mode)
	   (ansi-color-apply-on-region compilation-filter-start (point-max))))
       :hook (compilation-filter . qqq/colorize-compilation-buffer))
   #+end_src
** Relative line numbers
   #+begin_src emacs-lisp
     (use-package display-line-numbers
       :ensure nil
       :custom (display-line-numbers-type 'relative)
       :hook (prog-mode . display-line-numbers-mode))
   #+end_src
** Color theme
   #+begin_src emacs-lisp
     (use-package kaolin-themes
       :config
       (load-theme 'kaolin-dark t))
   #+end_src
** Writeroom
   Distraction-free writing mode
   #+begin_src emacs-lisp
     (use-package writeroom-mode
       :commands writeroom-mode)
   #+end_src
** Misc
   #+begin_src emacs-lisp
     (use-package page-break-lines)
     (use-package all-the-icons)
   #+end_src

* Tree-sitter
  #+begin_src emacs-lisp
    (use-package tree-sitter
      :init
      (use-package tree-sitter-langs)
      :config
      (global-tree-sitter-mode))
  #+end_src
   
* Tabs
  We use 4 spaces for tab
  #+begin_src emacs-lisp
    (setq custom-tab-width 4)
    (setq tab-width 4)
    (setq indent-tabs-mode nil)
    (setq tab-always-indent nil)
    (setq-default evil-shift-width custom-tab-width)
    (setq-default electric-indent-inhibit t)
  #+end_src

  Delete 4 spaces as tab
  #+begin_src emacs-lisp
    (setq backward-delete-char-untabify-method 'hungry)
  #+end_src

* Undo Tree
  #+begin_src emacs-lisp
    (use-package undo-tree
      :diminish
      :config
      (global-undo-tree-mode))
  #+end_src

* Keybindings
** Evil
   First of all, let's install evil
   #+begin_src emacs-lisp
     (setq evil-want-integration t)
     (setq evil-want-keybinding nil)

     (use-package evil
       :custom ((evil-undo-system 'undo-tree))
       :init
       (setq evil-search-module 'evil-search)
       (setq evil-ex-complete-emacs-commands nil)
       (setq evil-vsplit-window-right t)
       (setq evil-split-window-below t)
       (setq evil-shift-round nil)

       ; That doesn't work for some reason Idk
       (setq evil-want-C-u-scroll t)

       :config
       ; So we use this :(
       (evil-define-key 'normal 'global (kbd "C-u") 'evil-scroll-up)
       ; Backspace is so far away I just can't...
       (evil-define-key 'insert 'global (kbd "C-h") 'evil-delete-backward-char-and-join)
       (evil-define-key 'normal 'global (kbd "RET") 'evil-ret-and-indent)

       (evil-mode))
   #+end_src

*** Evil Collection
    #+begin_src emacs-lisp
      (use-package evil-collection
	:diminish
	:after evil
	:config
	(evil-collection-init))
    #+end_src
*** Evil Surround
    #+begin_src emacs-lisp
      (use-package evil-surround
	:after evil
	:commands
	(evil-surround-edit
	 evil-Surround-edit
	 evil-surround-region
	 evil-Surround-region)
	:init
	(evil-define-key 'operator global-map "s" 'evil-surround-edit)
	(evil-define-key 'operator global-map "S" 'evil-Surround-edit)
	(evil-define-key 'visual global-map "S" 'evil-surround-region)
	(evil-define-key 'visual global-map "gS" 'evil-Surround-region))
    #+end_src
*** Evil Commentary
    #+begin_src emacs-lisp
      (use-package evil-commentary
	:after evil
	:diminish
	:config
	(evil-commentary-mode))
    #+end_src
** General
   General.el is a package for handling keybindings, creating prefix (leader keys), infix keys, and stuff.
   We're using C-SPC and SPC as leader key for all the stuff we want.
   #+begin_src emacs-lisp
     (use-package general
       :after evil
       :config
       (general-evil-setup t)

       (general-create-definer qqq/leader-keys
	 :keymaps '(normal insert visual emacs)
	 :prefix "SPC"
	 :global-prefix "C-SPC")
       (general-create-definer qqq/local-leader-keys
	 :keymaps '(normal insert visual emacs)
	 :prefix "SPC m"
	 :global-prefix "C-SPC m"))
   #+end_src
** Some evil keybindings
   #+begin_src emacs-lisp
     (with-eval-after-load 'general
       (qqq/leader-keys "'" '(evil-commentary-line :which-key "comment line(s)")))
   #+end_src

* Dired
  #+begin_src emacs-lisp
    (require 'dired-x)
    (use-package dired
      :ensure nil
      :commands (dired dired-jump)
      :custom ((dired-dwim-target t))
      :config
      (evil-collection-define-key 'normal 'dired-mode-map
	"h" 'dired-single-up-directory
	"l" 'dired-single-buffer))

    (use-package dired-single
      :after dired)

    (use-package all-the-icons-dired
      :hook (dired-mode . all-the-icons-dired-mode))

    (with-eval-after-load 'general
      (qqq/leader-keys
	"d" '(:ignore t :which-key "Dired")
	"dd" '(dired :which-key "dwim")
	"do" '(dired-other-window :which-key "other window")))
  #+end_src

* Org Mode
  Org Mode is life changer, killer app, etc, you know whatsup, I
  guess.
  #+begin_src emacs-lisp
    (setq qqq/org-directory (concat (getenv "SYNCTHING") "org"))
    (defun qqq/get-org-file (file)
      (concat qqq/org-directory file))
    (use-package org
      :defer t
      :commands (org-capture org-agenda)
      :config
      (setq org-log-into-drawer t)
      (setq org-log-reschedule 'note)
      (setq org-refile-allow-creating-parent-nodes 'confirm)
      (setq org-refile-use-outline-path 'file)
      (setq org-indent-indentation-per-level 1)
      (setq org-hide-leading-stars t)
      (setq org-hide-emphasis-markers t)
      (setq org-blank-before-new-entry '((heading . nil) (plain-list-item . nil)))
      (setq org-cycle-separator-lines 1)
      (setq org-startup-with-inline-images t)
      (setq org-directory qqq/org-directory)
      (setq org-agenda-files (list org-directory))
      (setq org-refile-targets '((org-agenda-files . (:level . 1))))
      (setq org-todo-keywords
	    '((sequence "TODO(t)" "NEXT(n)" "WAIT(w@/!)" "|" "DONE(d!)" "CANCELED(c@)")))

      (setq org-return-follow-links t)

      (org-babel-do-load-languages
       'org-babel-load-languages
       '((emacs-lisp . t)
	 (python . t)))

      (setq org-confirm-babel-evaluate nil)
      (require 'ox-md)

      (require 'org-tempo)
      (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
      (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
      (add-to-list 'org-structure-template-alist '("py" . "src python")))
  #+end_src
** Org Agenda
   #+begin_src emacs-lisp
     (use-package org-agenda
       :ensure nil
       :after org
       :config
       (setq qqq/org-agenda-todo-view
	     `(("A" "Agenda"
		((agenda ""
			 ((org-agenda-span 'day)
			  (org-deadline-warning-days 365)))
		 (todo "TODO"
		       ((org-agenda-overriding-header "To Refile")
			(org-agenda-files `(,(qqq/get-org-file "/inbox.org")))))
		 (todo "NEXT"
		       ((org-agenda-overriding-header "In Progress")
			(org-agenda-files `(,(qqq/get-org-file "/next.org")
					    ,(qqq/get-org-file "/projects.org")))))
		 nil))))
       (setq org-agenda-custom-commands `,qqq/org-agenda-todo-view))
   #+end_src
** Org Capture
   #+begin_src emacs-lisp
     (with-eval-after-load 'org
       (setq org-capture-templates
	     `(("i" "inbox" entry (file ,(qqq/get-org-file "/inbox.org"))
		(file ,(qqq/get-org-file "/tmpl/task")))
	       ("l" "link" entry (file ,(qqq/get-org-file "/inbox.org"))
		(file ,(qqq/get-org-file "/tmpl/link")) :immediate-finish t))))
   #+end_src
** Org Drill
   Flashcards & spaced repetition
   #+begin_src emacs-lisp
     (use-package org-drill
       :after org
       :config
       (setq org-drill-add-random-noise-to-intervals-p t)
       (setq org-drill-learn-fraction 0.25)
       (setq org-drill-hint-separator "||")
       (setq org-drill-left-cloze-delimiter "<[")
       (setq org-drill-right-cloze-delimiter "]>"))
   #+end_src
** Org Download
   Drop images right into org mode buffer
   #+begin_src emacs-lisp
     (use-package org-download
       :after org)
   #+end_src
** Org Cliplink
   Paste org-mode link from clipboard
   #+begin_src emacs-lisp
     (use-package org-cliplink
       :after org)
   #+end_src
** Org Roam
   Zettelkasten, PogChamp!
   #+begin_src emacs-lisp
     (setq qqq/org-roam-directory (concat (getenv "SYNCTHING") "roam"))
     (use-package org-roam
       :hook (after-init . org-roam-mode)
       :diminish
       :defer t
       :init
       (setq org-roam-directory qqq/org-roam-directory)
       (setq org-roam-dailies-directory "daily/")
       (setq org-roam-dailies-capture-templates
	     '(("d" "default" entry
		#'org-roam-capture--get-point
		"* %?"
		:file-name "daily/%<%Y-%m-%d>"
		:head "#+title: %<%Y-%m-%d>\n\n")))
       (require 'org-roam-protocol))
   #+end_src
*** Org Roam Server
    #+begin_src emacs-lisp
      (use-package org-roam-server
	:after org-roam
	:config
	(setq org-roam-server-host "127.0.0.1"
	      org-roam-server-port 8080
	      org-roam-server-authenticate nil
	      org-roam-server-export-inline-images t
	      org-roam-server-server-files nil
	      org-roam-server-served-file-extensions '("pdf" "mp4" "ogv")
	      org-roam-server-network-poll t
	      org-roam-server-network-arrows nil
	      org-roam-server-network-label-truncate t
	      org-roam-server-network-label-truncate-length 60
	      org-roam-server-network-label-wrap-length 20))
    #+end_src
** Org Evil
   #+begin_src emacs-lisp
     (use-package evil-org
       :diminish
       :after (org evil)
       :hook (org-mode . evil-org-mode)
       :config
       (require 'evil-org-agenda)
       (evil-org-agenda-set-keys))
   #+end_src
** Org Keybindings
   #+begin_src emacs-lisp
     (qqq/leader-keys
       "o" '(:ignore t :which-key "Org")
       "oa" '(org-agenda :which-key "agenda")
       "oc" '(org-capture :which-key "capture")
       "od" '(org-drill :which-key "drill")
       "op" '(org-download-clipboard :which-key "clipboard image")
       "or" '(:ignore t :which-key "Roam")
       "ori" '(org-roam-insert :which-key "insert link")
       "oro" '(org-open-at-point :which-key "open link")
       "orf" '(org-roam-find-file :which-key "open file")
       "orb" '(org-roam :which-key "backlinks")
       "ord" '(:ignore t :which-key "Daily notes")
       "ordc" '(org-roam-dailies-capture-today :which-key "capture notes")
       "ordf" '(org-roam-dailies-find-today :which-key "open today notes"))
   #+end_src
   
* Spell checking
  I use hunspell for spellchecking, both for en and ru.
  #+begin_src emacs-lisp
    (with-eval-after-load "ispell"
      (setenv "LANG" "en_US")
      (setq ispell-program-name "hunspell")
      (setq ispell-dictionary "en_US,ru_RU")
      (ispell-set-spellchecker-params)
      (ispell-hunspell-add-multi-dic "en_US,ru_RU")
      (setq ispell-personal-dictionary "~/.emacs.d/.hunspell_personal"))

    (unless (file-exists-p "~/.emacs.d/.hunspell_personal")
      (shell-command "touch ~/.emacs.d/.hunspell_personal"))
  #+end_src

* Expand Region
  A small package to expand region of selection, very useful, bind it
  to SPC-=, you can expand more with hitting = or less with -
  #+begin_src emacs-lisp
    (use-package expand-region
      :commands er/expand-region
      :config
      (qqq/leader-keys "=" '(er/expand-region :which-key "expands region")))
  #+end_src
  
* Completion stuff
** Selectrum
   I like it. I used Ivy before, but I didn't use a lot of it aside
   from completion stuff
   #+begin_src emacs-lisp
     (use-package selectrum
       :config
       (selectrum-mode +1))
   #+end_src
*** Prescient
    Smart sort and filter!
    #+begin_src emacs-lisp
      (use-package selectrum-prescient
	:after selectrum
	:config
	(selectrum-prescient-mode +1)
	(prescient-persist-mode +1))
    #+end_src
*** Marginalia
    Shows cool annotations for completion stuff
    #+begin_src emacs-lisp
      (use-package marginalia
	:config
	(marginalia-mode))
    #+end_src
** Autocompletion
   Company is text-completion framework for emacs
   #+begin_src emacs-lisp
     (use-package company
       :diminish
       :custom
       (company-tooltip-limit 5)
       (company-idle-delay 0.1)
       (company-minimum-prefix-length 3)
       (company-selection-wrap-around t)
       (company-require-match 'never)
       :config
       (add-to-list 'company-backends 'company-capf)
       :hook (after-init . global-company-mode))
   #+end_src

* Search
** Ripgrep
   #+begin_src emacs-lisp
     (use-package ripgrep)
   #+end_src

* Project.el
  #+begin_src emacs-lisp
    (use-package project
      :config
      (add-to-list 'project-switch-commands '(magit-status "Magit" ?g))
      (qqq/leader-keys "p" '(:keymap project-prefix-map :which-key "project")))
  #+end_src
* Find File in Project
  #+begin_src emacs-lisp
    (use-package find-file-in-project
      :config
      (setq ffip-use-rust-fd t))
  #+end_src
* Hydra
  Hydra is some weird thing, I don't know if I really need it, but for
  now we're just using it for text scaling, idk
  #+begin_src emacs-lisp
    (use-package hydra
      :defer t
      :config
      (defhydra hydra-text-scale (:timeout 4)
	"scale text"
	("j" text-scale-increase "in")
	("k" text-scale-decrease "out")
	("f" nil "finished" :exit t))

      (qqq/leader-keys "t" '(hydra-text-scale/body :which-key "scale text"))

      (defhydra hydra-writeroom-width (:timeout 4)
	"writeroom width adjustment"
	("j" writeroom-increase-width "increase")
	("k" writeroom-decrease-width "decrease")
	("=" writeroom-adjust-width   "adjust (80)")
	("f" nil "finished" :exit t))
      (qqq/leader-keys "w" '(hydra-writeroom-width/body :which-key "writeroom adjustment")))
  #+end_src

* Magit
  I don't know how I worked with git before this package. This is a
  killer app for sure. Maybe even cooler than org mode.
  #+begin_src emacs-lisp
    (use-package magit
      :commands magit-status)
    (qqq/leader-keys "g" '(magit-status :which-key "magit"))
  #+end_src

* Programming
** Flycheck
   Linting and stuff
   #+begin_src emacs-lisp
     (use-package flycheck
       :diminish
       :hook (prog-mode . global-flycheck-mode))
   #+end_src
** LSP
   Language Server Protocol is cool thing, you don't really need IDE
   anymore (I guess)
   #+begin_src emacs-lisp
     (use-package lsp-mode
       :diminish
       :hook ((lsp-mode . lsp-enable-which-key-integration))
       :commands lsp lsp-deferred
       :config
       (setq lsp-headerline-breadcrumb-enable nil)
       (use-package lsp-ui
	 :after lsp
	 :commands lsp-ui-mode))
   #+end_src
** Web stuff
   HTML&CSS&JS, you know, all of this.
   #+begin_src emacs-lisp
     (use-package web-mode)
   #+end_src
*** Vue
    Vue-mode
    #+begin_src emacs-lisp
      (use-package vue-mode)
    #+end_src
** PHP
   Yeah, PHP...
   #+begin_src emacs-lisp
     (use-package php-mode
       :hook ((php-mode . lsp-deferred)))
   #+end_src
** Clojure
   The (almost) best language out there
   #+begin_src emacs-lisp
     (use-package clojure-mode)
     (use-package cider
       :commands cider)
   #+end_src
** Docker
   #+begin_src emacs-lisp
     (use-package docker)
   #+end_src
** Electric Pair Mode
   #+begin_src emacs-lisp
     (use-package electric-pair-mode
       :ensure nil
       :hook (prog-mode . electric-pair-mode))
   #+end_src

* FZF
  What's the point in life if there's no FZF in emacs?
  #+begin_src emacs-lisp
    (use-package fzf
      :init
      (setenv "FZF_DEFAULT_COMMAND" "fd --type f")
      (qqq/leader-keys "f" '(fzf-find-file :which-key "FZF")))
  #+end_src

  ;; Local Variables:
  ;; eval: (add-hook 'after-save-hook (lambda () (if (y-or-n-p "Reload?")(load-file user-init-file))) nil t)
  ;; eval: (add-hook 'after-save-hook (lambda () (if (y-or-n-p "Tangle?")(org-babel-tangle))) nil t)
  ;; End:
